# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='duration',
        ),
    ]
