# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='url',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
