# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration_min',
            field=models.IntegerField(default=0),
        ),
    ]
