# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0002_remove_podcast_publish_date'),
        ('YAPS', '0002_podcast_duration_min'),
    ]

    operations = [
    ]
