# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0002_remove_podcast_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(default=''),
        ),
    ]
