# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0003_merge_20180328_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='duration_min',
        ),
        migrations.AddField(
            model_name='podcast',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
