# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 23:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0003_podcast_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 1200)),
        ),
    ]
