# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0003_auto_20180322_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(null=True, upload_to='podcasts'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episode'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='episode'),
        ),
    ]
