# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0004_auto_20180322_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, default='podcasts/default.png', null=True, upload_to='podcasts'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
