# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0004_auto_20180328_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
