# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0005_auto_20180323_0144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.RemoveField(
            model_name='user',
            name='home_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='podcast',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
