# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0005_auto_20180323_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
