# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YAPS', '0006_auto_20180326_2321'),
        ('YAPS', '0007_auto_20180326_2056'),
    ]

    operations = [
    ]
